# Generated by Django 4.0.2 on 2022-03-09 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0004_rename_descrptions_reviewlist_descriptions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewlist',
            name='platform',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='xyz', to='watchlist_app.streamplatform'),
            preserve_default=False,
        ),
    ]
